### ISSUE TITLE
FE/yarn start:prod throws an error

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-angular#189]
## Problem description
Error: 
```
ROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.. Find more at https://angular.io/errors/NG0100
    at throwErrorIfNoChangesMode (core.js:6792:1)
    at bindingUpdated (core.js:12954:1)
    at bindingUpdated2 (core.js:12969:1)
    at pureFunction2Internal (core.js:25665:1)
    at Module.ɵɵpureFunction2 (core.js:25459:1)
    at AdminSidebarComponent_nav_0_Template (admin-sidebar.component.html:1:22)
    at executeTemplate (core.js:9614:1)
    at refreshView (core.js:9480:1)
    at refreshEmbeddedViews (core.js:10605:1)
    at refreshView (core.js:9504:1)
```

**Comment by milanmajchrak** [comment]
We already run DSpace on production for TUL and it is OK.
